# coding=utf-8
from powertrack.api import *
from datetime import datetime


p = PowerTrack(api="search")

categories = []
categories.append(["#trabajarhacercrecer",
"#votapp",
"@PPopular",
"Mariano Rajoy",
"@marianorajoy",
"@Sorayapp",
"Esperanza Aguirre",
"@EsperanzAguirre",
"Cristina Cifuentes",
"@ccifuentes",
"@CCifuentes2015",
"@AliciaSCamacho",
"Rita Barbera",
"@ritabarbera",
"Alberto Fabra",
"@AlbertoFabra",
"@gonzalezpons",
"M. Dolores Cospedal",
"@mdcospedal",
"J. Ignacio Zoido",
"@zoidoalcalde",
"@pablocasado_",
"Borja Semper",
"@bsemper",
"Luisa Fernanda Rudi",
"@LFRudi",
"@JRBauza",
"@JuanMa_Moreno"])

categories.append(["#yovotopsoe",
"#gobernarparalamayoría",
"@PSOE",
"Pedro Sánchez",
"Pedro Sanchez",
"@sanchezcastejon",
"Antonio M. Carmona",
"@AntonioMiguelC",
"Ángel Gabilondo",
"#Angelgabilondo",
"@equipoGabilondo",
"#solucionesjustas",
"@JoseantonioJun",
"@carmechacon",
"@BeatrizTalegon",
"@JuanEspadasSVQ",
"@Pedro_Zerolo",
"@EduMadina",
"@_Rubalcaba_",
"@ximopuig",
"Patxi Lopez",
"@patxilopez",
"@GFVara",
"@garciapage",
"@jaumecollboni",
"@javier_asturias",
"Susana Diaz",
"@_susanadiaz"])

categories.append(["#hagamoshistoria24m",
"@ahorapodemos",
"Pablo Iglesias",
"@Pablo_Iglesias_",
"Iñigo Errejón",
"@ierrejon",
"Manuela Carmena",
"@ManuelaCarmena",
"José Manuel López",
"@JoseManuel_Lop",
"Teresa Rodríguez",
"@TeresaRodr_",
"Carolina Bescansa",
"@CBescansa",
"Pablo Echenique",
"@pnique",
"@podemoszaragoza",
"Juan Carlos Monedero",
"@MonederoJC",
"Tania Sánchez",
"@Ainhat",
"Ahora Madrid",
"@AhoraMadrid",
"#ahoranosotras",
"#somosmanuela"])

categories.append(["#barcelonanaranja",
"#elcambiocs",
"#VotaCs",
"#ElCAMBIOSensato",
"#EspanaPideCambio",
"@CiudadanosCs",
"Albert Rivera",
"@Albert_Rivera",
"Ignacio Aguado",
"@ignacioaguado",
"Begoña Villacís",
"@begonavillacis",
"Carolina Punset",
"@CarolinaPunset",
"Inés Arrimadas",
"@InesArrimadas",
"Luis Garicano",
"@lugaricano",
"Carina Mejias"])

categories.append(["#estiempode",
"@iunida",
"#VotaIU",
"#EsTiempoDeIzquierda",
"Cayo Lara",
"@cayo_lara",
"Alberto Garzón",
"@agarzon",
"Gaspar Llamazares",
"@GLlamazares",
"Luis García Montero",
"@lgm_com",
"Raquel Lopez",
"@RaquelLopezIU"])

categories.append(["libres",
"#libres",
"#VotaUPYD",
"#YoVotoUPyD",
"@UPyD",
"Rosa Díez",
"@rosadiezupyd",
"Irene Lozano",
"@lozanoirene",
"Toni Cantó",
"@Tonicanto1",
"David Ortega",
"@davidortegaUPyD"])


new_file = True

for i, category in enumerate(categories):
    print "***", i
    new_job = p.jobs.create(datetime(2015, 5, 23, 14, 0), datetime(2015, 5, 23, 15, 0), "elpais", category)
    new_job.export_tweets(category=i + 1, append=False if new_file and i == 0 else True)
